const Menu = [
  {
    id: 1,
    title: "Rich dad poor dad",
    author: " By Robert and Sharon",
    price: "349",
    img: "/Images/img1.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "The Alchemist",
    author: "By Thomas Mathew",
    price: "299",
    img: "/Images/img2.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Harry Potter",
    author: " By J. K. Rowling",
    price: "389",
    img: "/Images/img3.png",
    amount: 1,
  },
  {
    id: 4,
    title: "Ruled",
    author: "By Elle Kennedy",
    price: "219",
    img: "/Images/img4.jfif",
    amount: 1,
  },
  {
    id: 5,
    title: "Believe in",
    author: "By Dr.Joseph",
    price: "179",
    img: "/Images/img5.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "How to fly",
    author: "By A.P.J Abdul Kalam",
    price: "349",
    img: "/Images/img6.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Life will change",
    author: "By Saranya Umakanthan",
    price: "239",
    img: "/Images/img7.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "The Universe",
    author: "By Matt khen",
    price: "289",
    img: "/Images/img8.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Read people like a book",
    author: "By Patrick King",
    price: "369",
    img: "/Images/img9.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Who will cry when you die",
    author: "By Robin Sharma",
    price: "319",
    img: "/Images/img20.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "3 Men in a boat",
    author: "By Jerome K ",
    price: "210",
    img: "/Images/img11.jfif",
    amount: 1,
  },
  {
    id: 12,
    title: "Thoughts to inspire",
    author: "By Swami Vivekananda",
    price: "429",
    img: "/Images/img12.jpg",
    amount: 1,
  },
  {
    id: 13,
    title: "Good to great",
    author: "By Jim Collins",
    price: "299",
    img: "/Images/img13.jfif",
    amount: 1,
  },
  {
    id: 14,
    title: "Master your Emotions",
    author: "By Thibaut Meurise",
    price: "369",
    img: "/Images/img144.jfif",
    amount: 1,
  },
];
export default Menu;
